### ISSUE TITLE
Celery pattern described in documentation no longer works.

### ISSUE THREAD

**Issue by wldcordeiro** [jezdez/django-configurations#101]
It looks like the `__all__` variable has been set in a way that the setup() function isn't exposed.  This makes this pattern not work http://django-configurations.readthedocs.org/en/latest/cookbook/#celery

**Comment by jpadilla** [comment]
Doing the following instead seems to work.

```python
from configurations import importer
importer.install()
```

**Comment by jezdez** [comment]
This was an issue of the documentation hosting configuration and should be back to the cookbook content that you can use with the currently released version 0.8. I've also made the "stable" docs the default on Readthedocs: http://django-configurations.readthedocs.org/en/stable/cookbook/#id4

**Comment by jpadilla** [comment]
@jezdez great, thanks!
