### ISSUE TITLE
the celery tutorial not work any more. the configurations.setup seems not exists any more.

### ISSUE THREAD

**Issue by hackrole** [jezdez/django-configurations#102]
I use celery 3.1.11. and not include djcelery on the django.settings:INSTALLED_APPS.

I run the celery with:
```bash
celery worker -a site -l info
```
but this give erorr.
```
django.core.exceptions.ImproperlyConfigured: django-configurations settings importer wasn't correctly installed. Please use one of the starter functions to install it as mentioned in the docs: http://django-configurations.readthedocs.org/
```

my celery.py look like this. I did not add the configurations.setup(), case the function not exists and will raise.
```
from __future__ import absolute_import

import os
from celery import Celery
from django.conf import settings


os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'site.settings')
os.environ.setdefault('DJANGO_CONFIGURATION', 'Dev')

app = Celery('stime')
app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)


@app.task()
def hello():
    print "hello world"
    return "hello"
```

**Comment by hackrole** [comment]
I add the follow line, now the celery can be startup, but I donot know how to use different settings for different env.
```
from __future__ import absolute_import

import os
from celery import Celery
from django.conf import settings


os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'site.settings')
os.environ.setdefault('DJANGO_CONFIGURATION', 'Dev')

from configurations import importer
importer.install()

app = Celery('stime')
app.config_from_object('django.conf.settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
```

 the option --configuration not exists, the only way seems to be define a  DJANGO_CONFIGURATION env. but I think the method was not good .

**Comment by jezdez** [comment]
This was an issue of the documentation hosting configuration and should be back to the cookbook content that you can use with the currently released version 0.8. I've also made the "stable" docs the default on Readthedocs: http://django-configurations.readthedocs.org/en/stable/cookbook/#id4

**Comment by Greyvend** [comment]
The documentation seems to have misleading instructions in the section for [Celery 3.1+](https://django-configurations.readthedocs.io/en/stable/cookbook/#id4) config or at least it doesn't work with Celery 4.0.2.

```python
configurations.setup()
```
causes the program to hang.

```python
from configurations import importer
importer.install()
```
instead works perfectly.

**Comment by blueyed** [comment]
@Greyvend 
Do you know if that would work also with Celery < 4?
A PR to fix this in the documentation makes sense anyway, and we can discuss it there then?!

**Comment by blueyed** [comment]
@Greyvend 
It seems to work for us with both Celery 3.1 and 4.

**Comment by Greyvend** [comment]
@blueyed do you have a Minimal Working Example (MWE) that confirms this?

P.S. Didn't start the discussion in documentation repo since [read-the-docs](https://django-configurations.readthedocs.io/en/stable/) GitHub link is broken.

**Comment by blueyed** [comment]
No minimal example, but used the same code (your first code snippet in `celery.py`) when upgrading to v4.
