### ISSUE TITLE
Django 1.8 compatible release

### ISSUE THREAD

**Issue by ttanner** [jezdez/django-configurations#105]
Django 1.8 has been released.
Please upload a compatible release ASAP.
Thank you

**Comment by DebauchedSloth** [comment]
+1

**Comment by andradei** [comment]
+1

I'm getting the following for any _manage.py_ command I run:

```
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from configurations.management import execute_from_command_line
  File "/Users/sargas/.virtualenvs/zfx/lib/python3.4/site-packages/configurations/management.py", line 1, in <module>
    from . import importer
  File "/Users/sargas/.virtualenvs/zfx/lib/python3.4/site-packages/configurations/importer.py", line 8, in <module>
    from django.core.management import LaxOptionParser
ImportError: cannot import name 'LaxOptionParser'
```

**Comment by JockeTF** [comment]
I'm having the same issue.

**Comment by theskumar** [comment]
+1. Waiting eagerly! :blush:

**Comment by maryokhin** [comment]
Broke because of [this](https://docs.djangoproject.com/en/dev/releases/1.8/#custom-test-management-command-arguments-through-test-runner).

**Comment by jezdez** [comment]
People of GitHub, I understand your eager waiting. But there is absolutely no need for +1ing this. I've seen the ticket once and don't need constant reminder via email. In fact I've worked hard for making sure things work nicely on 1.8 but haven't had the time yet to do the final round of release work.

I'm not working on this app during my day job, so looking at those emails – even writing this comment – **takes away time to work on Open Source software**. So. Please, have some patience, the app is not dead, but I'm just a human with a life.
