### ISSUE TITLE
Django 1.8 : Multiple --configuration arguments in management command

### ISSUE THREAD

**Issue by bsvetchine** [jezdez/django-configurations#109]
I just upgraded my django project for Django 1.8 and I get a strange problem with django-configurations :
 * I can call manually all the management commands without any problem (with or without the --configuration argument).
 * But when I launch my unit tests (using the django test management command), I face a optparse.OptionConflictError, conflicting option string(s): --configuration when Django is trying to flush the database.

If I print the "option_list" of the management commands called, I get several options "--configuration". It seems that each time the django call_command is called (within a management command), we add a new "--configuration" option.

**Comment by pydanny** [comment]
Please see https://github.com/jezdez/django-configurations/issues/105#issuecomment-88895512
