### ISSUE TITLE
Import Error on django 1.8 upgrade

### ISSUE THREAD

**Issue by yarbelk** [jezdez/django-configurations#111]
Upgrading to Django 1.8 - I get an import error LaxOptionParser from django.core.management - this has been removed  from that module.

```
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    from configurations.management import execute_from_command_line
  File "/Users/xxx/.virtualenvs/yyy/lib/python3.4/site-packages/configurations/management.py", line 1, in <module>
    from . import importer
  File "/Users/xxx/.virtualenvs/yyy/lib/python3.4/site-packages/configurations/importer.py", line 8, in <module>
    from django.core.management import LaxOptionParser
ImportError: cannot import name 'LaxOptionParser'
```

**Comment by mauricioabreu** [comment]
Did you try to find any previous errors like this using Github's search? Just this weed we had like 5 issues like this. Thanks!

**Comment by andradei** [comment]
They are aware of the issue. #105

**Comment by jimfmunro** [comment]
Also, it was addressed in https://github.com/jezdez/django-configurations/issues/65 

Using the latest master will work if you must have it now, at least it worked for me with django 1.8 and python 3.4

**Comment by yarbelk** [comment]
Thanks kindly
