### ISSUE TITLE
New PyPI release needed for Django 1.8 compatibility

### ISSUE THREAD

**Issue by troeger** [jezdez/django-configurations#112]
First, thanks for fixing #65 so fast.
 
We still have the situation that the latest django release and the latest django-configurations release in the PyPI do not work together, which basically renders the installation docs invalid. 

It might have low priority, but would it be possible to have an update on PyPI in the near future? Is there a release time plan?

**Comment by jezdez** [comment]
See https://github.com/jezdez/django-configurations/issues/105#issuecomment-88895512
