### ISSUE TITLE
Using a values.Value("WARNING") as a string causes <Value default: WARNING> in strings

### ISSUE THREAD

**Issue by martyzz1** [jezdez/django-configurations#114]
Similar to this https://github.com/jezdez/django-configurations/issues/68

Is it possible to have a values.StringValue("") type?

**Comment by martyzz1** [comment]
Hmmm I think this only applies to old pypi versions

**Comment by martyzz1** [comment]
Still does some quirky stuff when using variables in a logger config

LOG_LEVEL = values.Value("WARNING")

'': {
                  'handlers': ['console'],
                  'level': LOG_LEVEL,
                  'propagate': True,
              },

results in 'an exception WARNING' is not a valid log level.

if I use  'level': '{0}'.format(LOG_LEVEL),
I don't get an exception, but the logging level isn't set.

This is now using latest Master

**Comment by martyzz1** [comment]
if I use  

LOG_LEVEL = values.Value("WARNING").setup('LOG_LEVEL')

Then it works.  Seems clunky?

**Comment by jezdez** [comment]
This should be fixed in the next version.

**Comment by martyzz1** [comment]
thanks @jezdez
