### ISSUE TITLE
What is the plan for v0.9?

### ISSUE THREAD

**Issue by 5amfung** [jezdez/django-configurations#115]
A fix was merged in master but version hasn't been bumped to 0.9.  What is the plan for 0.9?  Should I keep using master assuming the version would not be bumped any time soon?

Thank you.

**Comment by misread** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django 1.8 users **seriously** need a new release.

**Comment by pydanny** [comment]
See #105 (comment)
