### ISSUE TITLE
Is there a way to customize the environment variable name for configuration?

### ISSUE THREAD

**Issue by alonisser** [jezdez/django-configurations#116]
I use this really  useful tool (thanks for that!)  with various django projects running in the same app server, But I can't customize the DJANGO_CONFIGURATION settings for different projects.  I would like to know if there is a possibility to passing an expected environment variable name (defaulting of course to DJANGO_CONFIGURATION) for django configuration to check for, similar to DATABASE_URL in [dj-database-url](https://github.com/kennethreitz/dj-database-url). If currently not possible are you open to the possibility of a pull request along those lines? Thanks

**Comment by pydanny** [comment]
There isn't a way to customize `DJANGO_CONFIGURATION` to another value (reference: https://github.com/jezdez/django-configurations/blob/master/configurations/importer.py#L17)

While it would be a relatively easy feature to add to the project, I argue that it doesn't fit the project's mission. Django-Configurations, as it endorses the 12 Factor app architecture, is designed for use when a single Django project is encapsulated on a single server (or VM or whatever).

**Comment by alonisser** [comment]
@pydanny wow, another of my python heros in this thread. I agree that deploying multiple Django projects on the same server isn't a great practice, but consider a microservices oriented environment (we have almost 40 and counting), setting up testings servers, or running the entire environment on my dev machine, while doable with vms, isn't fun or easy. So I think this feature has a place. Besides dj-database-url is a very popular Django utility and has this feature so it isn't complete blasphemy

**Comment by jezdez** [comment]
Hi @alonisser, thanks for your feature idea.

As @pydanny I also don't think this is in the scope of django-configurations as you can and should use your webserver's ability to set WSGI level environment variables like DJANGO_SETTINGS_MODULES and DJANGO_CONFIGURATION.

For example if you use Gunicorn, set the environment variable in the gunicorn call:

    gunicorn -b 127.0.0.1:8000 --env DJANGO_CONFIGURATION=Prod mysite.wsgi:application

(from http://docs.gunicorn.org/en/latest/settings.html#raw-env)

Process managers like Foreman or Supervisor also offer setting per-app environment variables.
