### ISSUE TITLE
configurations has no function called setup()

### ISSUE THREAD

**Issue by nangia** [jezdez/django-configurations#119]
Please take a look at the documentation for celery > 3.1 at

http://django-configurations.readthedocs.org/en/latest/cookbook/#celery

The example code asks for celery.py to contain the following code:

 import configurations
 configurations.setup()

However, as can be seen, for django-configurations 0.18, setup() is not a function in configurations. This is what I see as output of dir(configurations) after doing import configurations.

['Configuration', 'Settings', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'base', 'decorators', 'load_ipython_extension', 'pristinemethod', 'utils', 'values']

Can you please fix this to the appropriate code?

Regards,

Sandeep

**Comment by jezdez** [comment]
This was an issue of the documentation hosting configuration and should be back to the cookbook content that you can use with the currently released version 0.8. I've also made the "stable" docs the default on Readthedocs: http://django-configurations.readthedocs.org/en/stable/cookbook/#id4
