### ISSUE TITLE
no such option: --configuration

### ISSUE THREAD

**Issue by byashimov** [jezdez/django-configurations#120]
I'm not sure if you accept django 1.8 issues since #105, but this is happen when I use django-compressor command `compress`

```python
./manage.py compress --configuration=Prod
Usage: ./manage.py compress [options] 
Compress content outside of the request/response cycle
./manage.py: error: no such option: --configuration
```

django (1.8.3)
django-configurations (master)
django-compressor (1.4—1.5)

Everything else seems to work well here.

**Comment by asergeant01** [comment]
I too receive this error

**Comment by jezdez** [comment]
Closing as duplicate of #105.
