### ISSUE TITLE
Allow `Value` classes to be used outside of `Configuration` classes

### ISSUE THREAD

**Issue by mwarkentin** [jezdez/django-configurations#51]
[Originally discussed on twitter](https://twitter.com/jezdez/status/432207396086501376).

It would be nice to be able to use the [Values](http://django-configurations.readthedocs.org/en/latest/values/) classes without needing to actually be using a `Configuration` subclass.

**Comment by jezdez** [comment]
Yeah, I'd say this is possible now, just needs docs.
