### ISSUE TITLE
Problem using configurations when running multiple sites on the same VPS webserver ...

### ISSUE THREAD

**Issue by wgpubs** [jezdez/django-configurations#56]
It would seem that if I have multiple sites sitting on a production VPS, I'm going to have problems with environmental settings like "DJANGO_AWS_ACCESS_KEY_ID" as such items will generally vary from project-to-project.

For your consideration, I'd recommend a changing the convention to include the project name as well (e.g, "DJANGO_PROJECTNAME_AWS_ACCESS_KEY_ID"). 

Thanks.

**Comment by jezdez** [comment]
Thanks for the recommendation, but isolating environment variables should be easy enough to accomplish without blowing up the env variable names.

Some options: 
- use [envdir](https://pypi.python.org/pypi/envdir) or
- the soon to be released support for dotenv files, see 01e3f5837f3d0fed215d4e697425072219fdd964

I also opened #87 to document using Apache to set the environment variable in an isolated manner, in case your VPS is set up with that.
