### ISSUE TITLE
Error when trying to use another app which imports settings (django-debug-toolbar, Django 1.7/master)

### ISSUE THREAD

**Issue by blueyed** [jezdez/django-configurations#57]
(I think this is caused by using django-configurations, but have not verified it without)

The following import from settings.py causes an ImproperlyConfigured error:

    from debug_toolbar.middleware import show_toolbar as orig_show_toolbar

> ImproperlyConfigured: The SECRET_KEY setting must not be empty.

Some important entries from stepping through this:

    > …/django-debug-toolbar/debug_toolbar/middleware.py(14)<module>()
         13 
    ---> 14 from debug_toolbar.toolbar import DebugToolbar

    > …/django-debug-toolbar/debug_toolbar/settings.py(41)<module>()
         40 
    ---> 41 USER_CONFIG = getattr(settings, 'DEBUG_TOOLBAR_CONFIG', {})

Is it possible for django-configurations to handle this?

Apart from that a workaround might be to use django-configurations's setup method/hook.

**Comment by jezdez** [comment]
Hm, I think you can set up a custom show_toolbar helper and import the original inside of the function. That should fix the issue.

**Comment by blueyed** [comment]
It's ok to close this issue for now.

For the record, I was using the following already:

    def show_debug_toolbar(request):
        from debug_toolbar.middleware import show_toolbar as orig_show_toolbar
        if request.user and request.user.is_superuser:
            return True
        return orig_show_toolbar(request)

    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': 'config.settings.show_debug_toolbar',
        …
    }

I am not sure if I've been doing so already when reporting this issue.

Apart from that, recent fixes/merges in django-configurations might have
improved this behavior.
