### ISSUE TITLE
Conditional use of values in Configuration class

### ISSUE THREAD

**Issue by blueyed** [jezdez/django-configurations#59]
Is it possible to access a value in the Configuration class itself, like with:

    class Common(Configuration):
        if get_env_var('SENTRY_DSN', False):
            # Setup for Sentry

    class Common(Configuration):
        SENTRY_DSN = values.Value(environ_prefix="")
        if SENTRY_DSN:
            # Setup for Sentry

This is not possible, because the values get setup later, is it?

It would be nice if the documentation would mention / clarify this (preferably with an example using `os.environ` in a conditional).

**Comment by jezdez** [comment]
Yeah, I think this is somewhat fixed by #61.
