### ISSUE TITLE
Flexibility of DatabaseURLValue

### ISSUE THREAD

**Issue by schacki** [jezdez/django-configurations#70]
From my understanding, DatabaseURLValue currently can only handle a limited number of database options (as defined here https://docs.djangoproject.com/en/dev/ref/settings/#databases). E.g there is no way to define CONN_MAX_AGE or you cannot define any other database than "default".

Is my understanding correct? If so, I think this is a a rather strong limitation for the usage of django-configurations.

I am happy to provide a patch along the lines of providing an extra options parameter that holds the additional values. Or would you rather recommend to fix that at dj_database_url?

**Comment by jezdez** [comment]
This is a fix better suited for https://github.com/kennethreitz/dj-database-url
