### ISSUE TITLE
Celery configuration when configurations have been split over multiple files.

### ISSUE THREAD

**Issue by gciding** [jezdez/django-configurations#75]
Hi

I've hit a wall attempting to get Celery (3.1.14) to operate with Django 1.7 and django-configurations (0.8) when the configuration classes have been split across multiple files.  

By way of example, the https://github.com/pydanny/cookiecutter-django/tree/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D repo has split the project structure as below:

```
project_name/
    config/
        __init__.py
        common.py
        local.py
    manage.py
```

I've put a file ```celery.py``` in the config directory per the Celery and django-configuration instructions.

However, no matter what combination of settings/paths/locations for the celery.py or import statements I try -- I constantly get an ImportError saying it's ImproperlyConfigured. 

The only time I don't get that error is if I place the ```from .celery import app as celery_app``` above the common and local import lines in the ```config/__init__.py``` directory in which case the error regards not having a ```SECRET_KEY``` which indicates Celery is not loading the configuration/settings properly.

The environment variables in this case are: ```DJANGO_SETTINGS_ENVIRONMENT=config``` and ```DJANGO_CONFIGURATION=Local```.

A Gist with summary file info & the error is available here: https://gist.github.com/gciding/6935ee400f903ffd4bdc

Do you have any ideas on what the issue could be or where I should look to fix it (without having to put the files back into a single settings.py file again)?

Cheers

Goran

**Comment by jezdez** [comment]
This is unrelated to django-configurations, the way the cookiecutter template imports the configurations classes inside the `config/__init__.py` was part of the template ever since the settings were refactored. See https://github.com/pydanny/cookiecutter-django/commit/81576069f86087198ef2b6fb87c5f6f1f1e09cee#diff-1 for the original commit that changed it and that it matches what @alb3rto wrote above.
