### ISSUE TITLE
Using sphinx apidoc to load django modules

### ISSUE THREAD

**Issue by rrauenza** [jezdez/django-configurations#80]
I'm trying to figure out how to get sphinx to load my django modules to generate docs -- it is unable to load modules and I think it is due to django configurations.

I've added the following to sphinx's conf.py:

    sys.path.insert(0, os.path.abspath('../..'))
    print sys.path
    assert(os.environ['DJANGO_SETTINGS_MODULE'])
    assert(os.environ['DJANGO_CONFIGURATION'])
    from django.conf import settings
    import <myapp>.urls

And it fails on the <myapp>.urls import with: 

    ImproperlyConfigured: django-configurations settings importer wasn't correctly installed. Please use  one of the starter functions to install it as mentioned in the docs: http://django-configurations.readthedocs.org/

How do I bootstrap the config in a mostly non django script?

**Comment by jezdez** [comment]
I've added an extension point to django-configurations that effectively makes it a Sphinx extension. See https://github.com/jezdez/django-configurations/commit/f2a46fb009f9f50fe192bb243d2b5d63e3816341 for more info.
