### ISSUE TITLE
DatabaseURL() required

### ISSUE THREAD

**Issue by philippeluickx** [jezdez/django-configurations#95]
https://github.com/pydanny/cookiecutter-django/pull/139#issuecomment-76193352

*edit, because now I understand...

A good setup for configurations is using dj-database-url.
Using a URL leads to values.DatabaseURL()
This value should be required as an environment variable, just like SecretValue().

**Comment by jezdez** [comment]
There will be an optional `environ_required` parameter in the next version that will allow this pattern.

**Comment by philippeluickx** [comment]
Awesome, thanks!
